services:
  backend:
    container_name: podly_backend
    image: ghcr.io/noahkiss/podly_pure_podcasts/podly-backend:latest
    volumes:
      - ./config:/app/config
      - ./in:/app/in
      - ./srv:/app/srv
      - ./src:/app/src
      - ./scripts:/app/scripts
    ports:
      - 7638:5002
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      - CORS_ORIGINS=*
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    container_name: podly_frontend
    image: ghcr.io/noahkiss/podly_pure_podcasts/podly-frontend:latest
    ports:
      - 7637:80
    environment:
      - VITE_API_URL=http://localhost:7638
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:80/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
