name: Build and Push Docker Images

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/noahkiss/podly_pure_podcasts/podly-backend
            ghcr.io/noahkiss/podly_pure_podcasts/podly-frontend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-

      - name: Build and push Backend image (GPU)
        uses: docker/build-push-action@v6
        id: build-and-push-backend
        with:
          context: .
          file: ./docker/backend/Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            BASE_IMAGE=nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04
            CUDA_VERSION=12.4.1
            USE_GPU=true
          tags: |
            ghcr.io/noahkiss/podly_pure_podcasts/podly-backend:latest
            ghcr.io/noahkiss/podly_pure_podcasts/podly-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Frontend image
        uses: docker/build-push-action@v6
        id: build-and-push-frontend
        with:
          context: .
          file: ./Dockerfile.frontend
          push: true
          platforms: linux/amd64
          build-args: |
            VITE_API_URL=http://localhost:5002
          tags: |
            ghcr.io/noahkiss/podly_pure_podcasts/podly-frontend:latest
            ghcr.io/noahkiss/podly_pure_podcasts/podly-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image Digest
        run: |
          echo "Pushed backend image digest: ${{ steps.build-and-push-backend.outputs.digest }}"
          echo "Pushed frontend image digest: ${{ steps.build-and-push-frontend.outputs.digest }}"
